name: Build OpenWrt 24.10.1 x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib git libncurses-dev libssl-dev python3-venv \
          rsync unzip zlib1g-dev file wget python3 python3-pip
        pip3 install telegram-send

    - name: Clone OpenWrt Source
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v24.10.1
        cp ../feeds.conf.default ./
        cp ../config/minimal.config ./

    - name: Update & Install Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    
    - name: Load Default Config
      run: |
        cd openwrt
        make defconfig

    - name: Build Firmware
      run: |
        cd openwrt
        make download -j8
        make -j$(nproc) || make -j1 V=s

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-x86_64
        path: openwrt/bin/targets/x86/64/

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v24.10.1-x86_64-${{ github.run_number }}
        name: OpenWrt 24.10.1 x86_64 Build #${{ github.run_number }}
        files: openwrt/bin/targets/x86/64/*.img.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send Telegram Notification (optional)
      if: success() && env.TELEGRAM_BOT_TOKEN
      run: |
        echo "✅ OpenWrt 24.10.1 x86_64 构建完成，Release: https://github.com/${{ github.repository }}/releases/tag/${{ steps.create_release.outputs.tag_name }}" \
        | telegram-send --config /dev/null --chat-id "${{ secrets.TELEGRAM_CHAT_ID }}" --token "${{ secrets.TELEGRAM_BOT_TOKEN }}" --stdin
